---
# Longhorn role vars

longhorn_repo_name: longhorn
longhorn_repo_url: https://charts.longhorn.io
longhorn_chart_ref: longhorn/longhorn
longhorn_release_name: longhorn
longhorn_namespace: longhorn-system

longhorn_helm_chart_version: 1.11.0
longhorn_storage_mountpoint: /var/lib/longhorn

longhorn_values:
  defaultSettings:
    defaultDataPath: '{{ longhorn_storage_mountpoint }}'
    defaultReplicaCount: 2

