---

# Github Actions to do basic linting
# What we lint here:
# - Ansible playbooks and roles
# - YAML files (e.g., inventory, group_vars, etc.)
# - Shell scripts (if any)
# - Markdown files (e.g., README.md)

name: Lint and Validate

'on':
  pull_request:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up reports directory
        run: mkdir -p ${{ github.workspace }}/reports

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: |
          cd ${{ github.workspace }}/terraform/env
          for d in $(find . -mindepth 1 -maxdepth 1 -type d);
          do
            (cd $d && terraform init -backend=false && terraform validate) \
              | tee -a ${{ github.workspace }}/reports/terraform_validate.txt
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python linters
        run: pip install ansible-lint yamllint

      - name: Ansible Lint
        run: ansible-lint -p -v ${{ github.workspace }} | tee ${{ github.workspace }}/reports/ansible_lint.txt

      - name: YAML Lint
        run: |
          yamllint -c ${{ github.workspace }}/.yamllint-kubernetes \
            ${{ github.workspace }}/kubernetes \
            ${{ github.workspace }}/.github/ \
            | tee ${{ github.workspace }}/reports/yaml_lint.txt

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Markdown Lint
        run: |
          cd ${{ github.workspace }}
          markdownlint '**/*.md' --ignore node_modules --ignore vendor \
            | tee ${{ github.workspace }}/reports/markdown_lint.txt

      - name: Install Shellcheck
        run: sudo apt update && apt install -y shellcheck

      - name: Shellcheck
        run: |
          cd ${{ github.workspace }}/scripts
          for script in $(find . -type f -name "*.sh" | grep -v CONFIG.sh);
          do
            shellcheck -x "$script" | tee -a ${{ github.workspace }}/reports/shellcheck
          done
